# color theme
import = [
    "~/.config/alacritty/themes/themes/solarized_light.toml"
    #"~/.config/alacritty/themes/themes/gruvbox.toml"
]

[window]
decorations_theme_variant = "light"

dimensions.columns = 90 
dimensions.lines = 20

padding.x = 10
padding.y = 5 

decorations = "Full"

opacity = 1

title = "(づ｡◕‿‿◕｡)づ"
dynamic_title = false


[font]
normal = { family = "APL385 Unicode", style = "Regular" }
bold   = { family = "APL385 Unicode", style = "Bold" }
italic = { family = "APL385 Unicode", style = "Italic" }

size = 16.0

offset = { x=-1, y=0 }

# should prob just edit dirrectly in theme config
[colors]

[cursor]

